#!/bin/sh
# ------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

set -o errexit

if [ $# -ne 1 ]
  then
    echo "Expected argument: directory containing the JAR files of a GeoAPI implementation."
    exit 1
fi

CMD_HOME="`dirname "$( readlink -e "$0"; )";`"
cd "$CMD_HOME/../../../target"
jshell --class-path "binding-1.0-SNAPSHOT.jar:dependency/*:$1/*" "$CMD_HOME/imports.jsh"
